name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /app/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_EXPECTED_AGENCIES=3
    volumes:
      - ./server/config.ini:/app/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_AGENCY_ID=1
      - CLI_BET_NOMBRE=Laura
      - CLI_BET_APELLIDO=Lopez
      - CLI_BET_DOCUMENTO=10024987
      - CLI_BET_NACIMIENTO=1994-03-08
      - CLI_BET_NUMERO=5629
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_AGENCY_ID=2
      - CLI_BET_NOMBRE=Maria
      - CLI_BET_APELLIDO=Lopez
      - CLI_BET_DOCUMENTO=10006258
      - CLI_BET_NACIMIENTO=1990-10-17
      - CLI_BET_NUMERO=8781
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_AGENCY_ID=3
      - CLI_BET_NOMBRE=Carlos
      - CLI_BET_APELLIDO=Lopez
      - CLI_BET_DOCUMENTO=10005824
      - CLI_BET_NACIMIENTO=1993-01-24
      - CLI_BET_NUMERO=3796
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
