name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /app/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_EXPECTED_AGENCIES=5
    volumes:
      - ./server/config.ini:/app/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - AGENCY_ID=1
      - NOMBRE=Luis
      - APELLIDO=Martinez
      - DOCUMENTO=10027447
      - NACIMIENTO=1997-09-13
      - NUMERO=2356
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - AGENCY_ID=2
      - NOMBRE=Luis
      - APELLIDO=Diaz
      - DOCUMENTO=10031143
      - NACIMIENTO=1962-07-09
      - NUMERO=6051
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - AGENCY_ID=3
      - NOMBRE=Carlos
      - APELLIDO=Gonzalez
      - DOCUMENTO=10025369
      - NACIMIENTO=1970-01-06
      - NUMERO=9278
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - AGENCY_ID=4
      - NOMBRE=Maria
      - APELLIDO=Gonzalez
      - DOCUMENTO=10019288
      - NACIMIENTO=1998-07-14
      - NUMERO=3197
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - AGENCY_ID=5
      - NOMBRE=Ana
      - APELLIDO=Perez
      - DOCUMENTO=10019575
      - NACIMIENTO=1997-11-04
      - NUMERO=3483
    volumes:
      - ./client/config.yaml:/app/config.yaml
      - ./.data:/app/.data
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
